language: haskell
ghc:
  - 7.8
  - 7.6
  - '7.10'
install:
  - cabal install happy alex
  - cabal install doctest
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
  - cabal configure --enable-tests --enable-benchmarks -flib-Werror && cabal build && cabal test && make doctest && cabal bench
